### ISSUE TITLE
How do u use the hacks?

### ISSUE THREAD

**Issue by breezly101** [therealgliz/blooket-hacks#512]
Please help me!

**Comment by Lobster925** [comment]
Yes please help when I try to add coins it can't find my username in blooket.

**Comment by 21drake** [comment]
i need 7000 blookes

**Comment by TheCinnamonToastCrunch** [comment]
Follow this video to use the hacks.
https://user-images.githubusercontent.com/122049947/215201862-53935b7b-e356-4731-8348-b2c3b5a5c315.mov


P.S. This video was taken from a different repository. The person who wrote it is shenkeYT.

**Comment by KokoLuvsCats** [comment]
ok so currently the add tokens hack is not working, I am waiting for it to be fixed but for any hack, you want to copy it by clicking the copy button near the top right corner of the hack. Then bookmark any tab because the URL will be changed anyway and name it and place it in the folder you want. Then click more and delete all the URL. Then type javascript with this symbol next to it : in the place where the URL goes. It should look like this:

javascript: 

Then paste in the hack and the final thing should look like this:

javascript: your blooket hack

Finally, to use the hack it depends on what it is. For the token adder make sure you are logged in, click play, click on the bookmark, click ok, and then you should have max tokens for the day. You can do this every day to get a ton of tokens.

For others all you have to do is click the bookmark for example if I'm playing crypto hack I can click the add crypto bookmark I have and input the amount I want. FWI it doesn't add the crypto/whatever currency you are using, it resets it to that amount so if you have 3b and you add 4m you now only have 4m.

Hope this helped!
